name: install cypress
on: push
jobs:
  check-cypress-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install cypress
      - run: npx cypress --version
